In [2]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,3,0])
print('A+B = ',np.add(A,B))
print('A-B = ',np.subtract(A,B))

A+B =  [5 5 3]
A-B =  [-3 -1  3]


In [5]:
C = np.array([[1,2,3],
             [1,1,1]])
D = np.array([[4,3,9,9],
             [1,1,2,2],
             [4,2,1,1]])

#矩阵与矩阵相乘
print('np.dot(C,D) = ',np.dot(C,D))
print('np.matmul(C,D) = ',np.matmul(C,D))
print('  C@D = ',np.matmul(C,D))

#元素与元素相乘
print('np.multiply(D,D) = ',np.multiply(D,D))
print('  D*D = ',D*D)

np.dot(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
np.matmul(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
  C@D =  [[18 11 16 16]
 [ 9  6 12 12]]
np.multiply(D,D) =  [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]
  D*D =  [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]


In [6]:
m_4_4 = np.array([[1,2,3,4],
                 [3,2,1,4],
                 [5,4,6,7],
                 [11,12,13,14]])
m_3_4_2 = np.array([
                   [
                       [2,3],
                       [11,9],
                       [32,21],
                       [28,17]
                   ],
                   [
                       [2,3],
                       [1,9],
                       [3,21],
                       [28,7]
                   ],
                   [
                       [2,3],
                       [1,9],
                       [3,21],
                       [28,7]
                   ]
                    ])

In [8]:
print(m_4_4.shape)
print(m_3_4_2.shape)

(4, 4)
(3, 4, 2)


In [9]:
#dot  把m_4_4分成4块，每块是1_4；把把m_3_4_2分成3块，每块是4_2. 做1_4*4_2运算
print('4x4*3x4x2 dot:\n {} \n'.format(np.dot(m_4_4,m_3_4_2)))

4x4*3x4x2 dot:
 [[[232 152]
  [125 112]
  [125 112]]

 [[172 116]
  [123  76]
  [123  76]]

 [[442 296]
  [228 226]
  [228 226]]

 [[962 652]
  [465 512]
  [465 512]]] 



In [10]:
#matmul  把m_3_4_2分成3块，每块做4_4 * 4_2运算
print('4x4*3x4x2 matmul:\n {} \n'.format(np.matmul(m_4_4,m_3_4_2)))

4x4*3x4x2 matmul:
 [[[232 152]
  [172 116]
  [442 296]
  [962 652]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]] 



In [11]:
np.dot(m_4_4,m_3_4_2[0,:,:])

array([[232, 152],
       [172, 116],
       [442, 296],
       [962, 652]])

In [12]:
np.matmul(m_4_4,m_3_4_2[:,:,0].T)

array([[232, 125, 125],
       [172, 123, 123],
       [442, 228, 228],
       [962, 465, 465]])

In [1]:
m_3_4_2[:,:,0].T

NameError: name 'm_3_4_2' is not defined